name: Attendize

on:
  pull_request:
    types: [assigned, edited, opened, synchronize, reopened]
  push:
    branches:
      - next
      - master
      - v2*

jobs:
  laravel-build-and-test:
    runs-on: self-host
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      uses: php-actions/composer@v4
      with:
        command: install
        args: --no-ansi --prefer-dist
        php_version: 7.4
        composer_version: 2
        interaction: no
        suggest: no
        dev: yes
        progress: no
        quiet: no
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      uses: php-actions/composer@v4
      with:
        command: exec phpunit
        php_version: 7.4
        composer_version: 2
        interaction: no
        suggest: no
        dev: yes
        progress: no
        quiet: no
  
  deploy:
    runs-on: ubuntu-latest
    needs: laravel-build-and-test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'tokensys'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_a847ea18adbd4dfeba1b09683a393c55 }}
          package: .
  
